repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # lint
  - repo: local
    hooks:
      - id: make-lint
        name: make lint
        entry: make lint
        language: system
        types: [swift]
        pass_filenames: false

  # secret
  - repo: local
    hooks:
      - id: make-gitleaks
        name: make gitleaks/staged
        entry: make gitleaks/staged
        language: system
        pass_filenames: false

  # security
  - repo: local
    hooks:
      - id: make-semgrep
        name: make semgrep
        entry: make semgrep
        language: system
        pass_filenames: false
