// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

package schema

import (
	"time"
)

// Collection names
const (
	CollectionDomains = "domains"
)

// DomainPath returns the document path for a domain.
func DomainPath(domainID string) string {
	return "domains/" + domainID
}

type Topic struct {
	Id       string `firestore:"id" json:"id" yaml:"id"`
	Title    string `firestore:"title" json:"title" yaml:"title"`
	ImageUrl string `firestore:"imageUrl" json:"imageUrl" yaml:"imageUrl"`
}

func (t *Topic) GetId() string {
	if t == nil {
		return ""
	}
	return t.Id
}

func (t *Topic) GetTitle() string {
	if t == nil {
		return ""
	}
	return t.Title
}

func (t *Topic) GetImageUrl() string {
	if t == nil {
		return ""
	}
	return t.ImageUrl
}

type WorkTheme struct {
	ID          string    `firestore:"-" json:"id" yaml:"id"`
	Title       string    `firestore:"title" json:"title" yaml:"title"`
	Description string    `firestore:"description" json:"description" yaml:"description"`
	Topics      []*Topic  `firestore:"topics" json:"topics" yaml:"topics"`
	Color       string    `firestore:"color" json:"color" yaml:"color"`
	CreatedAt   time.Time `firestore:"createdAt,serverTimestamp" json:"createdAt" yaml:"createdAt"`
	UpdatedAt   time.Time `firestore:"updatedAt,serverTimestamp" json:"updatedAt" yaml:"updatedAt"`
}

func (w *WorkTheme) GetTitle() string {
	if w == nil {
		return ""
	}
	return w.Title
}

func (w *WorkTheme) GetDescription() string {
	if w == nil {
		return ""
	}
	return w.Description
}

func (w *WorkTheme) GetTopics() []*Topic {
	if w == nil {
		return nil
	}
	return w.Topics
}

func (w *WorkTheme) GetColor() string {
	if w == nil {
		return ""
	}
	return w.Color
}

func (w *WorkTheme) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WorkTheme) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *WorkTheme) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

// TopicFields contains field names for Topic.
var TopicFields = struct {
	Id       string
	Title    string
	ImageUrl string
}{
	Id:       "id",
	Title:    "title",
	ImageUrl: "imageUrl",
}

// WorkThemeFields contains field names for WorkTheme.
var WorkThemeFields = struct {
	Id          string
	Title       string
	Description string
	Topics      string
	Color       string
	CreatedAt   string
	UpdatedAt   string
}{
	Id:          "id",
	Title:       "title",
	Description: "description",
	Topics:      "topics",
	Color:       "color",
	CreatedAt:   "createdAt",
	UpdatedAt:   "updatedAt",
}
