// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

package schema

import (
	"time"
)

// Collection names
const (
	CollectionDomains = "domains"
)

// DomainPath returns the document path for a domain.
func DomainPath(domainID string) string {
	return "domains/" + domainID
}

type Topic struct {
	Id       string `firestore:"id" json:"id" yaml:"id"`
	Code     string `firestore:"code" json:"code" yaml:"code"`
	Title    string `firestore:"title" json:"title" yaml:"title"`
	ImageUrl string `firestore:"imageUrl" json:"imageUrl" yaml:"imageUrl"`
}

func (t *Topic) GetId() string {
	if t == nil {
		return ""
	}
	return t.Id
}

func (t *Topic) GetCode() string {
	if t == nil {
		return ""
	}
	return t.Code
}

func (t *Topic) GetTitle() string {
	if t == nil {
		return ""
	}
	return t.Title
}

func (t *Topic) GetImageUrl() string {
	if t == nil {
		return ""
	}
	return t.ImageUrl
}

type Domain struct {
	ID          string    `firestore:"-" json:"id" yaml:"id"`
	Title       string    `firestore:"title" json:"title" yaml:"title"`
	Description string    `firestore:"description" json:"description" yaml:"description"`
	Topics      []*Topic  `firestore:"topics" json:"topics" yaml:"topics"`
	IconUrl     string    `firestore:"iconUrl" json:"iconUrl" yaml:"iconUrl"`
	CreatedAt   time.Time `firestore:"createdAt,serverTimestamp" json:"createdAt" yaml:"createdAt"`
	UpdatedAt   time.Time `firestore:"updatedAt,serverTimestamp" json:"updatedAt" yaml:"updatedAt"`
}

func (d *Domain) GetTitle() string {
	if d == nil {
		return ""
	}
	return d.Title
}

func (d *Domain) GetDescription() string {
	if d == nil {
		return ""
	}
	return d.Description
}

func (d *Domain) GetTopics() []*Topic {
	if d == nil {
		return nil
	}
	return d.Topics
}

func (d *Domain) GetIconUrl() string {
	if d == nil {
		return ""
	}
	return d.IconUrl
}

func (d *Domain) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *Domain) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

func (d *Domain) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// TopicFields contains field names for Topic.
var TopicFields = struct {
	Id       string
	Code     string
	Title    string
	ImageUrl string
}{
	Id:       "id",
	Code:     "code",
	Title:    "title",
	ImageUrl: "imageUrl",
}

// DomainFields contains field names for Domain.
var DomainFields = struct {
	Id          string
	Title       string
	Description string
	Topics      string
	IconUrl     string
	CreatedAt   string
	UpdatedAt   string
}{
	Id:          "id",
	Title:       "title",
	Description: "description",
	Topics:      "topics",
	IconUrl:     "iconUrl",
	CreatedAt:   "createdAt",
	UpdatedAt:   "updatedAt",
}
