// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

package schema

import (
	"time"
)

// Collection names
const (
	CollectionGithub_pulls = "github_pulls"
)

// Github_pullPath returns the document path for a github_pull.
func Github_pullPath(githubPullID string) string {
	return "github_pulls/" + githubPullID
}

type GithubPullStatus string

const (
	GithubPullStatusOpen   GithubPullStatus = "open"
	GithubPullStatusMerged GithubPullStatus = "merged"
	GithubPullStatusClosed GithubPullStatus = "closed"
)

type GithubPull struct {
	ID            string           `firestore:"-" json:"id" yaml:"id"`
	DomainId      string           `firestore:"domainId" json:"domainId" yaml:"domainId"`
	TopicId       string           `firestore:"topicId" json:"topicId" yaml:"topicId"`
	PrNumber      int              `firestore:"prNumber" json:"prNumber" yaml:"prNumber"`
	Title         string           `firestore:"title" json:"title" yaml:"title"`
	Status        GithubPullStatus `firestore:"status" json:"status" yaml:"status"`
	FirstCommitAt *time.Time       `firestore:"firstCommitAt" json:"firstCommitAt" yaml:"firstCommitAt"`
	ClosedAt      *time.Time       `firestore:"closedAt" json:"closedAt" yaml:"closedAt"`
	FullNote      string           `firestore:"fullNote" json:"fullNote" yaml:"fullNote"`
	Url           string           `firestore:"url" json:"url" yaml:"url"`
	Repository    string           `firestore:"repository" json:"repository" yaml:"repository"`
	CreatedAt     time.Time        `firestore:"createdAt" json:"createdAt" yaml:"createdAt"`
	UpdatedAt     time.Time        `firestore:"updatedAt,serverTimestamp" json:"updatedAt" yaml:"updatedAt"`
}

func (g *GithubPull) GetDomainId() string {
	if g == nil {
		return ""
	}
	return g.DomainId
}

func (g *GithubPull) GetTopicId() string {
	if g == nil {
		return ""
	}
	return g.TopicId
}

func (g *GithubPull) GetPrNumber() int {
	if g == nil {
		return 0
	}
	return g.PrNumber
}

func (g *GithubPull) GetTitle() string {
	if g == nil {
		return ""
	}
	return g.Title
}

func (g *GithubPull) GetStatus() GithubPullStatus {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GithubPull) GetFirstCommitAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.FirstCommitAt
}

func (g *GithubPull) GetClosedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.ClosedAt
}

func (g *GithubPull) GetFullNote() string {
	if g == nil {
		return ""
	}
	return g.FullNote
}

func (g *GithubPull) GetUrl() string {
	if g == nil {
		return ""
	}
	return g.Url
}

func (g *GithubPull) GetRepository() string {
	if g == nil {
		return ""
	}
	return g.Repository
}

func (g *GithubPull) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GithubPull) GetUpdatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.UpdatedAt
}

func (g *GithubPull) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GithubPullFields contains field names for GithubPull.
var GithubPullFields = struct {
	Id            string
	DomainId      string
	TopicId       string
	PrNumber      string
	Title         string
	Status        string
	FirstCommitAt string
	ClosedAt      string
	FullNote      string
	Url           string
	Repository    string
	CreatedAt     string
	UpdatedAt     string
}{
	Id:            "id",
	DomainId:      "domainId",
	TopicId:       "topicId",
	PrNumber:      "prNumber",
	Title:         "title",
	Status:        "status",
	FirstCommitAt: "firstCommitAt",
	ClosedAt:      "closedAt",
	FullNote:      "fullNote",
	Url:           "url",
	Repository:    "repository",
	CreatedAt:     "createdAt",
	UpdatedAt:     "updatedAt",
}
