// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

package schema

import (
	"time"
)

// Collection names
const (
	CollectionWork_logs = "work_logs"
)

// Work_logPath returns the document path for a work_log.
func Work_logPath(workLogID string) string {
	return "work_logs/" + workLogID
}

type WorkLog struct {
	ID        string    `firestore:"-" json:"id" yaml:"id"`
	DomainId  string    `firestore:"domainId" json:"domainId" yaml:"domainId"`
	TopicId   string    `firestore:"topicId" json:"topicId" yaml:"topicId"`
	Content   string    `firestore:"content" json:"content" yaml:"content"`
	StartedAt time.Time `firestore:"startedAt" json:"startedAt" yaml:"startedAt"`
	EndedAt   time.Time `firestore:"endedAt" json:"endedAt" yaml:"endedAt"`
	UserId    string    `firestore:"userId" json:"userId" yaml:"userId"`
	UserName  string    `firestore:"userName" json:"userName" yaml:"userName"`
	UserIcon  string    `firestore:"userIcon" json:"userIcon" yaml:"userIcon"`
	CreatedAt time.Time `firestore:"createdAt,serverTimestamp" json:"createdAt" yaml:"createdAt"`
	UpdatedAt time.Time `firestore:"updatedAt,serverTimestamp" json:"updatedAt" yaml:"updatedAt"`
}

func (w *WorkLog) GetDomainId() string {
	if w == nil {
		return ""
	}
	return w.DomainId
}

func (w *WorkLog) GetTopicId() string {
	if w == nil {
		return ""
	}
	return w.TopicId
}

func (w *WorkLog) GetContent() string {
	if w == nil {
		return ""
	}
	return w.Content
}

func (w *WorkLog) GetStartedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.StartedAt
}

func (w *WorkLog) GetEndedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.EndedAt
}

func (w *WorkLog) GetUserId() string {
	if w == nil {
		return ""
	}
	return w.UserId
}

func (w *WorkLog) GetUserName() string {
	if w == nil {
		return ""
	}
	return w.UserName
}

func (w *WorkLog) GetUserIcon() string {
	if w == nil {
		return ""
	}
	return w.UserIcon
}

func (w *WorkLog) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WorkLog) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *WorkLog) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

// WorkLogFields contains field names for WorkLog.
var WorkLogFields = struct {
	Id        string
	DomainId  string
	TopicId   string
	Content   string
	StartedAt string
	EndedAt   string
	UserId    string
	UserName  string
	UserIcon  string
	CreatedAt string
	UpdatedAt string
}{
	Id:        "id",
	DomainId:  "domainId",
	TopicId:   "topicId",
	Content:   "content",
	StartedAt: "startedAt",
	EndedAt:   "endedAt",
	UserId:    "userId",
	UserName:  "userName",
	UserIcon:  "userIcon",
	CreatedAt: "createdAt",
	UpdatedAt: "updatedAt",
}
