// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

package schema

import (
	"time"
)

// Collection names
const (
	CollectionWork_topics = "work_topics"
)

// Work_topicPath returns the document path for a work_topic.
func Work_topicPath(workTopicID string) string {
	return "work_topics/" + workTopicID
}

type WorkTopic struct {
	ID          string    `firestore:"-" json:"id" yaml:"id"`
	Title       string    `firestore:"title" json:"title" yaml:"title"`
	Description string    `firestore:"description" json:"description" yaml:"description"`
	ImageUrl    string    `firestore:"imageUrl" json:"imageUrl" yaml:"imageUrl"`
	CreatedAt   time.Time `firestore:"createdAt,serverTimestamp" json:"createdAt" yaml:"createdAt"`
	UpdatedAt   time.Time `firestore:"updatedAt,serverTimestamp" json:"updatedAt" yaml:"updatedAt"`
}

func (w *WorkTopic) GetTitle() string {
	if w == nil {
		return ""
	}
	return w.Title
}

func (w *WorkTopic) GetDescription() string {
	if w == nil {
		return ""
	}
	return w.Description
}

func (w *WorkTopic) GetImageUrl() string {
	if w == nil {
		return ""
	}
	return w.ImageUrl
}

func (w *WorkTopic) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WorkTopic) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *WorkTopic) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

// WorkTopicFields contains field names for WorkTopic.
var WorkTopicFields = struct {
	Id          string
	Title       string
	Description string
	ImageUrl    string
	CreatedAt   string
	UpdatedAt   string
}{
	Id:          "id",
	Title:       "title",
	Description: "description",
	ImageUrl:    "imageUrl",
	CreatedAt:   "createdAt",
	UpdatedAt:   "updatedAt",
}
