package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"generator/internal/parser"
)

// Generator generates Go code from schema definitions.
type Generator struct {
	schema *parser.Schema
	outDir string
}

// New creates a new Generator.
func New(schema *parser.Schema, outDir string) *Generator {
	return &Generator{
		schema: schema,
		outDir: outDir,
	}
}

// Generate generates Go files for all collections.
func (g *Generator) Generate() error {
	for _, name := range g.schema.Collections.Keys {
		collection := g.schema.Collections.Values[name]
		if err := g.generateCollectionFile(name, collection); err != nil {
			return fmt.Errorf("generating %s: %w", name, err)
		}
	}
	return nil
}

func (g *Generator) generateCollectionFile(name string, col parser.Collection) error {
	var buf bytes.Buffer

	// Header
	buf.WriteString("// Code generated by youdoyou-firestore-kit. DO NOT EDIT.\n\n")
	buf.WriteString("package schema\n\n")

	// Collect all collections (including subcollections)
	var allCollections []collectionInfo
	collectAllCollections(name, col, false, &allCollections)

	// Collect all models needed for this collection (preserving order)
	modelsToGenerate := make(map[string]bool)
	var modelOrder []string
	g.collectModelsForCollection(col, modelsToGenerate, &modelOrder)

	// Collect imports
	imports := g.collectImportsForModels(modelsToGenerate)
	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for _, imp := range imports {
			buf.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		buf.WriteString(")\n\n")
	}

	// Generate collection constants
	generateCollectionConstants(&buf, allCollections)

	// Generate path functions
	generatePathFunctions(&buf, allCollections)

	// Generate models in dependency order (referenced models first)
	generatedModels := make(map[string]bool)
	orderedModels, err := g.orderModelsByDependency(modelsToGenerate, modelOrder)
	if err != nil {
		return err
	}

	for _, modelName := range orderedModels {
		if generatedModels[modelName] {
			continue
		}
		model, exists := g.schema.Models.Values[modelName]
		if !exists {
			continue
		}
		g.generateModel(&buf, modelName, model, generatedModels)
	}

	// Generate field constants for each model
	for _, modelName := range orderedModels {
		model, exists := g.schema.Models.Values[modelName]
		if !exists {
			continue
		}
		generateFieldConstants(&buf, modelName, model)
	}

	// Format code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting code: %w\n%s", err, buf.String())
	}

	// Write file
	fileName := strings.ToLower(singularize(name)) + ".go"
	filePath := filepath.Join(g.outDir, fileName)
	if err := os.WriteFile(filePath, formatted, 0600); err != nil {
		return fmt.Errorf("writing file: %w", err)
	}

	return nil
}

func (g *Generator) collectModelsForCollection(col parser.Collection, models map[string]bool, modelOrder *[]string) {
	if col.Model != "" {
		g.collectModelAndDependencies(col.Model, models, modelOrder)
	}
	for _, name := range col.Subcollections.Keys {
		subCol := col.Subcollections.Values[name]
		g.collectModelsForCollection(subCol, models, modelOrder)
	}
}

func (g *Generator) collectModelAndDependencies(modelName string, models map[string]bool, modelOrder *[]string) {
	if models[modelName] {
		return
	}
	models[modelName] = true
	*modelOrder = append(*modelOrder, modelName)

	model, exists := g.schema.Models.Values[modelName]
	if !exists {
		return
	}

	for _, fieldName := range model.Fields.Keys {
		field := model.Fields.Values[fieldName]
		if field.ItemModel != "" {
			g.collectModelAndDependencies(field.ItemModel, models, modelOrder)
		}
		if field.Model != "" {
			g.collectModelAndDependencies(field.Model, models, modelOrder)
		}
	}
}

func (g *Generator) orderModelsByDependency(models map[string]bool, modelOrder []string) ([]string, error) {
	// Topological sort preserving YAML order: models with no dependencies come first
	var result []string
	added := make(map[string]bool)

	// Keep iterating until all models are added
	for len(added) < len(models) {
		progress := false
		for _, modelName := range modelOrder {
			if !models[modelName] || added[modelName] {
				continue
			}
			// Check if all dependencies are added
			model := g.schema.Models.Values[modelName]
			allDepsAdded := true
			for _, fieldName := range model.Fields.Keys {
				field := model.Fields.Values[fieldName]
				if field.ItemModel != "" && models[field.ItemModel] && !added[field.ItemModel] {
					allDepsAdded = false
					break
				}
				if field.Model != "" && models[field.Model] && !added[field.Model] {
					allDepsAdded = false
					break
				}
			}
			if allDepsAdded {
				result = append(result, modelName)
				added[modelName] = true
				progress = true
			}
		}
		// No model could be added this pass: the remaining models form a cycle.
		if !progress {
			return nil, fmt.Errorf("circular dependency detected among models: %v", remainingModels(models, added))
		}
	}
	return result, nil
}

// remainingModels returns models present in the set but not yet added, for error reporting.
func remainingModels(models, added map[string]bool) []string {
	var remaining []string
	for name := range models {
		if !added[name] {
			remaining = append(remaining, name)
		}
	}
	return remaining
}

func (g *Generator) collectImportsForModels(models map[string]bool) []string {
	imports := make(map[string]bool)

	for modelName := range models {
		model, exists := g.schema.Models.Values[modelName]
		if !exists {
			continue
		}
		for _, fieldName := range model.Fields.Keys {
			field := model.Fields.Values[fieldName]
			if field.Type == "timestamp" || field.Type == "server_timestamp" {
				imports["time"] = true
			}
		}
	}

	result := make([]string, 0, len(imports))
	for imp := range imports {
		result = append(result, imp)
	}
	// Note: go/format will sort imports automatically
	return result
}

func (g *Generator) generateModel(buf *bytes.Buffer, modelName string, model parser.Model, generated map[string]bool) {
	if generated[modelName] {
		return
	}
	generated[modelName] = true

	// Collect enums from this model (preserving YAML order)
	var enums []enumDef
	for _, fieldName := range model.Fields.Keys {
		field := model.Fields.Values[fieldName]
		if len(field.Enum) > 0 {
			enums = append(enums, enumDef{
				Name:   modelName + toPascalCase(fieldName),
				Values: field.Enum,
			})
		}
	}

	// Generate enum types (order preserved from YAML)
	for _, enum := range enums {
		buf.WriteString(fmt.Sprintf("type %s string\n\n", enum.Name))
		buf.WriteString("const (\n")
		for _, v := range enum.Values {
			constName := enum.Name + toPascalCase(v)
			buf.WriteString(fmt.Sprintf("\t%s %s = %q\n", constName, enum.Name, v))
		}
		buf.WriteString(")\n\n")
	}

	// Determine if this model has an ID field
	hasIDField := false
	for _, fieldName := range model.Fields.Keys {
		field := model.Fields.Values[fieldName]
		if field.Type == "id" {
			hasIDField = true
			break
		}
	}

	// Generate struct
	buf.WriteString(fmt.Sprintf("type %s struct {\n", modelName))

	// Use field names in YAML order
	fieldNames := model.Fields.Keys

	// Generate fields
	for _, fieldName := range fieldNames {
		field := model.Fields.Values[fieldName]

		// Skip id field in struct body (handled separately)
		if field.Type == "id" {
			buf.WriteString("\tID string `firestore:\"-\" json:\"id\" yaml:\"id\"`\n")
			continue
		}

		goType := g.fieldToGoType(fieldName, field, modelName)
		goName := toPascalCase(fieldName)
		firestoreTag := fieldName
		if field.Type == "server_timestamp" {
			firestoreTag = fieldName + ",serverTimestamp"
		}
		tag := fmt.Sprintf("`firestore:%q json:%q yaml:%q`", firestoreTag, fieldName, fieldName)
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", goName, goType, tag))
	}

	buf.WriteString("}\n\n")

	// Generate getters with nil check
	for _, fieldName := range fieldNames {
		field := model.Fields.Values[fieldName]

		// Skip id field for getter (use ID directly)
		if field.Type == "id" {
			continue
		}

		goType := g.fieldToGoType(fieldName, field, modelName)
		goName := toPascalCase(fieldName)
		receiver := strings.ToLower(string(modelName[0]))
		zeroValue := g.zeroValueForType(goType)
		buf.WriteString(fmt.Sprintf("func (%s *%s) Get%s() %s {\n", receiver, modelName, goName, goType))
		buf.WriteString(fmt.Sprintf("\tif %s == nil {\n", receiver))
		buf.WriteString(fmt.Sprintf("\t\treturn %s\n", zeroValue))
		buf.WriteString("\t}\n")
		buf.WriteString(fmt.Sprintf("\treturn %s.%s\n", receiver, goName))
		buf.WriteString("}\n\n")
	}

	// Add getter for ID if model has id field
	if hasIDField {
		receiver := strings.ToLower(string(modelName[0]))
		buf.WriteString(fmt.Sprintf("func (%s *%s) GetID() string {\n", receiver, modelName))
		buf.WriteString(fmt.Sprintf("\tif %s == nil {\n", receiver))
		buf.WriteString("\t\treturn \"\"\n")
		buf.WriteString("\t}\n")
		buf.WriteString(fmt.Sprintf("\treturn %s.ID\n", receiver))
		buf.WriteString("}\n\n")
	}
}

func (g *Generator) fieldToGoType(fieldName string, field parser.Field, modelName string) string {
	switch field.Type {
	case "string":
		if len(field.Enum) > 0 {
			return modelName + toPascalCase(fieldName)
		}
		return "string"
	case "integer":
		return "int"
	case "float":
		return "float64"
	case "boolean":
		return "bool"
	case "timestamp":
		if field.Optional {
			return "*time.Time"
		}
		return "time.Time"
	case "server_timestamp":
		return "time.Time"
	case "array":
		if field.ItemModel != "" {
			return "[]*" + field.ItemModel
		}
		if field.ItemType != "" {
			return "[]" + g.primitiveToGoType(field.ItemType)
		}
		return "[]interface{}"
	case "map":
		if field.Model != "" {
			return "*" + field.Model
		}
		return "map[string]interface{}"
	default:
		// Handle vector(N) type
		if strings.HasPrefix(field.Type, "vector(") {
			return "[]float64"
		}
		return "interface{}"
	}
}

func (g *Generator) primitiveToGoType(t string) string {
	switch t {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "float":
		return "float64"
	case "boolean":
		return "bool"
	default:
		return "interface{}"
	}
}

func (g *Generator) zeroValueForType(goType string) string {
	switch goType {
	case "string":
		return `""`
	case "int":
		return "0"
	case "float64":
		return "0"
	case "bool":
		return "false"
	case "time.Time":
		return "time.Time{}"
	default:
		if strings.HasPrefix(goType, "*") || strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") {
			return "nil"
		}
		// For enum types (like Role, Type), return empty string
		return `""`
	}
}

type enumDef struct {
	Name   string
	Values []string
}

func toPascalCase(s string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func singularize(s string) string {
	if strings.HasSuffix(s, "ies") {
		return s[:len(s)-3] + "y"
	}
	if strings.HasSuffix(s, "ses") {
		return s[:len(s)-2]
	}
	if strings.HasSuffix(s, "s") && !strings.HasSuffix(s, "ss") {
		return s[:len(s)-1]
	}
	return s
}

// collectionInfo holds information about a collection for code generation.
type collectionInfo struct {
	Name            string
	Path            string
	IsSubcollection bool
}

// collectAllCollections collects all collections (including subcollections) from a collection tree.
func collectAllCollections(name string, col parser.Collection, isSubcollection bool, result *[]collectionInfo) {
	*result = append(*result, collectionInfo{
		Name:            name,
		Path:            col.Path,
		IsSubcollection: isSubcollection,
	})
	for _, subName := range col.Subcollections.Keys {
		subCol := col.Subcollections.Values[subName]
		collectAllCollections(subName, subCol, true, result)
	}
}

// generateCollectionConstants generates collection name constants.
func generateCollectionConstants(buf *bytes.Buffer, collections []collectionInfo) {
	buf.WriteString("// Collection names\n")
	buf.WriteString("const (\n")
	for _, col := range collections {
		constName := "Collection" + toPascalCase(col.Name)
		buf.WriteString(fmt.Sprintf("\t%s = %q\n", constName, col.Name))
	}
	buf.WriteString(")\n\n")
}

// generatePathFunctions generates path functions for collections.
func generatePathFunctions(buf *bytes.Buffer, collections []collectionInfo) {
	for _, col := range collections {
		// Skip if no path is defined
		if col.Path == "" {
			continue
		}

		singularName := toPascalCase(singularize(col.Name))
		vars := extractPathVars(col.Path)

		// Build function parameters
		params := make([]string, len(vars))
		for i, v := range vars {
			params[i] = v + " string"
		}
		paramStr := strings.Join(params, ", ")

		// Generate collection path function for subcollections only
		if col.IsSubcollection && len(vars) > 0 {
			collectionPath := removeLastPathSegment(col.Path)
			collectionPathExpr := buildPathExpr(collectionPath)
			// Collection path function uses all vars except the last one
			collectionVars := vars[:len(vars)-1]
			collectionParams := make([]string, len(collectionVars))
			for i, v := range collectionVars {
				collectionParams[i] = v + " string"
			}
			collectionParamStr := strings.Join(collectionParams, ", ")

			buf.WriteString(fmt.Sprintf("// %sCollectionPath returns the collection path for %s.\n", singularName, col.Name))
			buf.WriteString(fmt.Sprintf("func %sCollectionPath(%s) string {\n", singularName, collectionParamStr))
			buf.WriteString(fmt.Sprintf("\treturn %s\n", collectionPathExpr))
			buf.WriteString("}\n\n")
		}

		// Generate document path function
		pathExpr := buildPathExpr(col.Path)
		buf.WriteString(fmt.Sprintf("// %sPath returns the document path for a %s.\n", singularName, singularize(col.Name)))
		buf.WriteString(fmt.Sprintf("func %sPath(%s) string {\n", singularName, paramStr))
		buf.WriteString(fmt.Sprintf("\treturn %s\n", pathExpr))
		buf.WriteString("}\n\n")
	}
}

// generateFieldConstants generates field name constants for a model.
func generateFieldConstants(buf *bytes.Buffer, modelName string, model parser.Model) {
	buf.WriteString(fmt.Sprintf("// %sFields contains field names for %s.\n", modelName, modelName))
	buf.WriteString(fmt.Sprintf("var %sFields = struct {\n", modelName))

	// Struct field definitions
	for _, fieldName := range model.Fields.Keys {
		goName := toPascalCase(fieldName)
		buf.WriteString(fmt.Sprintf("\t%s string\n", goName))
	}
	buf.WriteString("}{\n")

	// Struct field values
	for _, fieldName := range model.Fields.Keys {
		goName := toPascalCase(fieldName)
		// For id type, the field name in JSON is "id"
		field := model.Fields.Values[fieldName]
		firestoreFieldName := fieldName
		if field.Type == "id" {
			firestoreFieldName = "id"
		}
		buf.WriteString(fmt.Sprintf("\t%s: %q,\n", goName, firestoreFieldName))
	}
	buf.WriteString("}\n\n")
}

// extractPathVars extracts path variables from a path template.
// e.g., "threads/{threadID}/messages/{messageID}" → ["threadID", "messageID"]
func extractPathVars(path string) []string {
	var vars []string
	start := -1
	for i, c := range path {
		if c == '{' {
			start = i + 1
		} else if c == '}' && start != -1 {
			vars = append(vars, path[start:i])
			start = -1
		}
	}
	return vars
}

// buildPathExpr builds a Go string concatenation expression from a path template.
// e.g., "threads/{threadID}" → `"threads/" + threadID`
func buildPathExpr(path string) string {
	var parts []string
	var current strings.Builder
	inVar := false

	for i := 0; i < len(path); i++ {
		c := path[i]
		if c == '{' {
			if current.Len() > 0 {
				parts = append(parts, fmt.Sprintf("%q", current.String()))
				current.Reset()
			}
			inVar = true
		} else if c == '}' {
			if current.Len() > 0 {
				parts = append(parts, current.String())
				current.Reset()
			}
			inVar = false
		} else {
			current.WriteByte(c)
		}
	}
	if current.Len() > 0 {
		if inVar {
			parts = append(parts, current.String())
		} else {
			parts = append(parts, fmt.Sprintf("%q", current.String()))
		}
	}

	return strings.Join(parts, " + ")
}

// removeLastPathSegment removes the last /{var} segment from a path.
// e.g., "threads/{threadID}/messages/{messageID}" → "threads/{threadID}/messages"
func removeLastPathSegment(path string) string {
	lastSlash := strings.LastIndex(path, "/")
	if lastSlash == -1 {
		return path
	}
	return path[:lastSlash]
}
