package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"generator/internal/parser"
)

// SwiftGenerator generates Swift code from schema definitions.
type SwiftGenerator struct {
	schema *parser.Schema
	outDir string
}

// NewSwift creates a new SwiftGenerator.
func NewSwift(schema *parser.Schema, outDir string) *SwiftGenerator {
	return &SwiftGenerator{
		schema: schema,
		outDir: outDir,
	}
}

// Generate generates Swift files for all collections.
func (g *SwiftGenerator) Generate() error {
	for _, name := range g.schema.Collections.Keys {
		collection := g.schema.Collections.Values[name]
		if err := g.generateCollectionFile(name, collection); err != nil {
			return fmt.Errorf("generating %s: %w", name, err)
		}
	}
	return nil
}

func (g *SwiftGenerator) generateCollectionFile(name string, col parser.Collection) error {
	var buf bytes.Buffer

	// Header
	buf.WriteString("// Code generated by youdoyou-firestore-kit. DO NOT EDIT.\n\n")
	buf.WriteString("@preconcurrency import FirebaseFirestore\n")
	buf.WriteString("import Foundation\n")

	// Collect all collections (including subcollections)
	var allCollections []collectionInfo
	collectAllCollections(name, col, false, &allCollections)

	// Generate Collection enums
	for _, collInfo := range allCollections {
		g.generateCollectionEnum(&buf, collInfo)
	}

	// Collect all models needed for this collection (preserving order)
	modelsToGenerate := make(map[string]bool)
	var modelOrder []string
	g.collectModelsForCollection(col, modelsToGenerate, &modelOrder)

	// Order models: main model first, then rest in dependency order
	orderedModels, err := g.orderModelsByDependency(modelsToGenerate, modelOrder)
	if err != nil {
		return err
	}
	orderedModels = reorderMainFirst(col.Model, orderedModels)

	// Generate each model
	generatedModels := make(map[string]bool)
	for _, modelName := range orderedModels {
		if generatedModels[modelName] {
			continue
		}
		model, exists := g.schema.Models.Values[modelName]
		if !exists {
			continue
		}
		generatedModels[modelName] = true

		// Top-level enum types (before Fields enum)
		g.generateEnumTypes(&buf, modelName, model)

		// Fields enum
		g.generateFieldsEnum(&buf, modelName, model)

		// Struct + init
		g.generateStruct(&buf, modelName, model)
	}

	// Write file
	singularName := snakeToPascalCase(singularize(name))
	fileName := singularName + ".swift"
	filePath := filepath.Join(g.outDir, fileName)
	if err := os.WriteFile(filePath, buf.Bytes(), 0600); err != nil {
		return fmt.Errorf("writing file: %w", err)
	}

	return nil
}

// reorderMainFirst moves the main collection model to the front of the list.
func reorderMainFirst(mainModel string, ordered []string) []string {
	if mainModel == "" {
		return ordered
	}
	result := []string{mainModel}
	for _, m := range ordered {
		if m != mainModel {
			result = append(result, m)
		}
	}
	return result
}

// generateCollectionEnum generates a {Model}Collection enum with name and path helpers.
func (g *SwiftGenerator) generateCollectionEnum(buf *bytes.Buffer, collInfo collectionInfo) {
	singularName := snakeToPascalCase(singularize(collInfo.Name))
	vars := extractPathVars(collInfo.Path)

	buf.WriteString(fmt.Sprintf("\npublic enum %sCollection {\n", singularName))

	// Collection name constant
	buf.WriteString(fmt.Sprintf("    public static let name = %q\n", collInfo.Name))

	// For subcollections, generate collectionPath function
	if collInfo.IsSubcollection && len(vars) > 0 {
		collectionPath := removeLastPathSegment(collInfo.Path)
		collVars := vars[:len(vars)-1]

		params := make([]string, len(collVars))
		for i, v := range collVars {
			params[i] = fmt.Sprintf("_ %s: String", toCamelCase(v))
		}
		paramStr := strings.Join(params, ", ")

		buf.WriteString(fmt.Sprintf("\n    public static func collectionPath(%s) -> String {\n", paramStr))
		buf.WriteString(fmt.Sprintf("        %s\n", buildSwiftInterpolation(collectionPath)))
		buf.WriteString("    }\n")
	}

	// Document path function
	// For top-level collections (single param), use simple "_ id: String"
	// For subcollections (multiple params), use the schema variable names
	var params []string
	if !collInfo.IsSubcollection && len(vars) == 1 {
		params = []string{"_ id: String"}
	} else {
		params = make([]string, len(vars))
		for i, v := range vars {
			params[i] = fmt.Sprintf("_ %s: String", toCamelCase(v))
		}
	}
	paramStr := strings.Join(params, ", ")

	buf.WriteString(fmt.Sprintf("\n    public static func documentPath(%s) -> String {\n", paramStr))
	if !collInfo.IsSubcollection && len(vars) == 1 {
		// For top-level: use "id" directly since that's the parameter name
		collName := strings.Split(collInfo.Path, "/")[0]
		buf.WriteString(fmt.Sprintf("        \"%s/\\(id)\"\n", collName))
	} else {
		buf.WriteString(fmt.Sprintf("        %s\n", buildSwiftInterpolation(collInfo.Path)))
	}
	buf.WriteString("    }\n")

	buf.WriteString("}\n")
}

// generateEnumTypes generates top-level enum types for fields with enum values.
func (g *SwiftGenerator) generateEnumTypes(buf *bytes.Buffer, modelName string, model parser.Model) {
	for _, fieldName := range model.Fields.Keys {
		field := model.Fields.Values[fieldName]
		if len(field.Enum) == 0 {
			continue
		}

		enumName := modelName + toPascalCase(fieldName)
		buf.WriteString(fmt.Sprintf("\npublic enum %s: String, Codable, Sendable {\n", enumName))
		for _, v := range field.Enum {
			camelCase := toCamelCase(v)
			if camelCase == v {
				buf.WriteString(fmt.Sprintf("    case %s\n", v))
			} else {
				buf.WriteString(fmt.Sprintf("    case %s = %q\n", camelCase, v))
			}
		}
		buf.WriteString("}\n")
	}
}

// generateFieldsEnum generates a {Model}Fields enum with static let constants.
func (g *SwiftGenerator) generateFieldsEnum(buf *bytes.Buffer, modelName string, model parser.Model) {
	buf.WriteString(fmt.Sprintf("\npublic enum %sFields {\n", modelName))
	for _, fieldName := range model.Fields.Keys {
		buf.WriteString(fmt.Sprintf("    public static let %s = %q\n", toCamelCase(fieldName), fieldName))
	}
	buf.WriteString("}\n")
}

// generateStruct generates a Swift struct with init.
func (g *SwiftGenerator) generateStruct(buf *bytes.Buffer, modelName string, model parser.Model) {
	// Determine conformances
	hasIDField := false
	for _, fieldName := range model.Fields.Keys {
		field := model.Fields.Values[fieldName]
		if field.Type == "id" || fieldName == "id" {
			hasIDField = true
			break
		}
	}

	conformances := "Codable, Sendable"
	if hasIDField {
		conformances = "Codable, Identifiable, Sendable"
	}

	buf.WriteString(fmt.Sprintf("\npublic struct %s: %s {\n", modelName, conformances))

	// Generate fields
	for _, fieldName := range model.Fields.Keys {
		field := model.Fields.Values[fieldName]

		if field.Type == "id" {
			buf.WriteString("    @DocumentID public var id: String?\n")
			continue
		}

		swiftName := toCamelCase(fieldName)

		if field.Type == "server_timestamp" {
			buf.WriteString(fmt.Sprintf("    @ServerTimestamp public var %s: Date?\n", swiftName))
			continue
		}

		swiftType := g.fieldToSwiftType(fieldName, field, modelName)
		buf.WriteString(fmt.Sprintf("    public var %s: %s\n", swiftName, swiftType))
	}

	// Generate init
	g.generateInit(buf, modelName, model)

	buf.WriteString("}\n")
}

// generateInit generates a public init excluding id (type: id) and server_timestamp fields.
func (g *SwiftGenerator) generateInit(buf *bytes.Buffer, modelName string, model parser.Model) {
	type initParam struct {
		name         string
		swiftType    string
		defaultValue string
	}

	var params []initParam
	for _, fieldName := range model.Fields.Keys {
		field := model.Fields.Values[fieldName]

		// Skip DocumentID and server_timestamp
		if field.Type == "id" || field.Type == "server_timestamp" {
			continue
		}

		swiftName := toCamelCase(fieldName)
		swiftType := g.fieldToSwiftType(fieldName, field, modelName)

		var defaultVal string
		if field.Optional {
			defaultVal = "nil"
		} else if field.Type == "array" {
			defaultVal = "[]"
		}

		params = append(params, initParam{
			name:         swiftName,
			swiftType:    swiftType,
			defaultValue: defaultVal,
		})
	}

	if len(params) == 0 {
		return
	}

	buf.WriteString("\n    public init(\n")
	for i, p := range params {
		suffix := ","
		if i == len(params)-1 {
			suffix = ""
		}
		if p.defaultValue != "" {
			buf.WriteString(fmt.Sprintf("        %s: %s = %s%s\n", p.name, p.swiftType, p.defaultValue, suffix))
		} else {
			buf.WriteString(fmt.Sprintf("        %s: %s%s\n", p.name, p.swiftType, suffix))
		}
	}
	buf.WriteString("    ) {\n")
	for _, p := range params {
		buf.WriteString(fmt.Sprintf("        self.%s = %s\n", p.name, p.name))
	}
	buf.WriteString("    }\n")
}

func (g *SwiftGenerator) fieldToSwiftType(fieldName string, field parser.Field, modelName string) string {
	optional := field.Optional

	switch field.Type {
	case "string":
		if len(field.Enum) > 0 {
			return modelName + toPascalCase(fieldName)
		}
		if optional {
			return "String?"
		}
		return "String"
	case "integer":
		if optional {
			return "Int?"
		}
		return "Int"
	case "float":
		if optional {
			return "Double?"
		}
		return "Double"
	case "boolean":
		if optional {
			return "Bool?"
		}
		return "Bool"
	case "timestamp":
		if optional {
			return "Date?"
		}
		return "Date"
	case "server_timestamp":
		return "Date?" // handled with property wrapper
	case "array":
		var itemType string
		if field.ItemModel != "" {
			itemType = field.ItemModel
		} else if field.ItemType != "" {
			itemType = g.primitiveToSwiftType(field.ItemType)
		} else {
			itemType = "Any"
		}
		return fmt.Sprintf("[%s]", itemType)
	case "map":
		if field.Model != "" {
			if optional {
				return fmt.Sprintf("%s?", field.Model)
			}
			return field.Model
		}
		return "[String: Any]"
	case "id":
		return "String?"
	default:
		if strings.HasPrefix(field.Type, "vector(") {
			return "[Double]"
		}
		return "Any"
	}
}

func (g *SwiftGenerator) primitiveToSwiftType(t string) string {
	switch t {
	case "string":
		return "String"
	case "integer":
		return "Int"
	case "float":
		return "Double"
	case "boolean":
		return "Bool"
	default:
		return "Any"
	}
}

func (g *SwiftGenerator) collectModelsForCollection(col parser.Collection, models map[string]bool, modelOrder *[]string) {
	if col.Model != "" {
		g.collectModelAndDependencies(col.Model, models, modelOrder)
	}
	for _, name := range col.Subcollections.Keys {
		subCol := col.Subcollections.Values[name]
		g.collectModelsForCollection(subCol, models, modelOrder)
	}
}

func (g *SwiftGenerator) collectModelAndDependencies(modelName string, models map[string]bool, modelOrder *[]string) {
	if models[modelName] {
		return
	}
	models[modelName] = true
	*modelOrder = append(*modelOrder, modelName)

	model, exists := g.schema.Models.Values[modelName]
	if !exists {
		return
	}

	for _, fieldName := range model.Fields.Keys {
		field := model.Fields.Values[fieldName]
		if field.ItemModel != "" {
			g.collectModelAndDependencies(field.ItemModel, models, modelOrder)
		}
		if field.Model != "" {
			g.collectModelAndDependencies(field.Model, models, modelOrder)
		}
	}
}

func (g *SwiftGenerator) orderModelsByDependency(models map[string]bool, modelOrder []string) ([]string, error) {
	var result []string
	added := make(map[string]bool)

	for len(added) < len(models) {
		progress := false
		for _, modelName := range modelOrder {
			if !models[modelName] || added[modelName] {
				continue
			}
			model := g.schema.Models.Values[modelName]
			allDepsAdded := true
			for _, fieldName := range model.Fields.Keys {
				field := model.Fields.Values[fieldName]
				if field.ItemModel != "" && models[field.ItemModel] && !added[field.ItemModel] {
					allDepsAdded = false
					break
				}
				if field.Model != "" && models[field.Model] && !added[field.Model] {
					allDepsAdded = false
					break
				}
			}
			if allDepsAdded {
				result = append(result, modelName)
				added[modelName] = true
				progress = true
			}
		}
		// No model could be added this pass: the remaining models form a cycle.
		if !progress {
			return nil, fmt.Errorf("circular dependency detected among models: %v", remainingModels(models, added))
		}
	}
	return result, nil
}

// snakeToPascalCase converts snake_case to PascalCase (e.g., "github_pull" → "GithubPull").
func snakeToPascalCase(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, part := range parts {
		if part != "" {
			result.WriteString(toPascalCase(part))
		}
	}
	return result.String()
}

// toCamelCase converts snake_case or kebab-case to camelCase.
func toCamelCase(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	parts := strings.Split(s, "_")

	if len(parts) == 0 {
		return s
	}

	result := parts[0]
	for i := 1; i < len(parts); i++ {
		if parts[i] != "" {
			result += toPascalCase(parts[i])
		}
	}
	return result
}

// buildSwiftInterpolation converts a path template to a Swift string interpolation.
// e.g., "threads/{threadID}" → `"threads/\(threadID)"`
func buildSwiftInterpolation(path string) string {
	var result strings.Builder
	result.WriteByte('"')

	for i := 0; i < len(path); i++ {
		c := path[i]
		if c == '{' {
			result.WriteString("\\(")
			// Find closing brace and convert var name to camelCase
			j := i + 1
			for j < len(path) && path[j] != '}' {
				j++
			}
			varName := toCamelCase(path[i+1 : j])
			result.WriteString(varName)
			result.WriteByte(')')
			i = j // skip past '}'
		} else {
			result.WriteByte(c)
		}
	}

	result.WriteByte('"')
	return result.String()
}
