package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yu-fukunaga/youdoyou-intelligence/firebase/generator/internal/parser"
)

func newSwiftGen(t *testing.T, schema *parser.Schema) (*SwiftGenerator, string) {
	t.Helper()
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, "schema")
	if err := os.MkdirAll(outDir, 0750); err != nil {
		t.Fatalf("failed to create outDir: %v", err)
	}
	return NewSwift(schema, outDir), tmpDir
}

func readSwiftFile(t *testing.T, dir, name string) string {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(dir, "schema", name)) // #nosec G304 -- dir is t.TempDir() and name is a hardcoded test filename
	if err != nil {
		t.Fatalf("failed to read %s: %v", name, err)
	}
	return string(content)
}

func TestSwiftGenerate_Header(t *testing.T) {
	schema := &parser.Schema{
		Models: makeModels(map[string]parser.Model{
			"User": {Fields: makeFields(map[string]parser.Field{"name": {Type: "string"}})},
		}),
		Collections: makeCollections(map[string]parser.Collection{
			"users": {Model: "User"},
		}),
	}

	gen, tmpDir := newSwiftGen(t, schema)
	if err := gen.Generate(); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	code := readSwiftFile(t, tmpDir, "User.swift")

	if !strings.Contains(code, "// Code generated by youdoyou-firestore-kit. DO NOT EDIT.") {
		t.Error("expected generated code header")
	}
	if !strings.Contains(code, "import FirebaseFirestore") {
		t.Error("expected FirebaseFirestore import")
	}
	if !strings.Contains(code, "import Foundation") {
		t.Error("expected Foundation import")
	}
}

func TestSwiftGenerate_CollectionEnum(t *testing.T) {
	schema := &parser.Schema{
		Models: makeModels(map[string]parser.Model{
			"User": {Fields: makeFields(map[string]parser.Field{"name": {Type: "string"}})},
		}),
		Collections: makeCollections(map[string]parser.Collection{
			"users": {Model: "User"},
		}),
	}

	gen, tmpDir := newSwiftGen(t, schema)
	if err := gen.Generate(); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	code := readSwiftFile(t, tmpDir, "User.swift")

	if !strings.Contains(code, "public enum UserCollection") {
		t.Error("expected UserCollection enum")
	}
	if !strings.Contains(code, `public static let name = "users"`) {
		t.Error("expected collection name constant")
	}
	if !strings.Contains(code, "public static func documentPath") {
		t.Error("expected documentPath function")
	}
}

func TestSwiftGenerate_BasicStruct(t *testing.T) {
	schema := &parser.Schema{
		Models: makeModels(map[string]parser.Model{
			"User": {
				Fields: makeFields(map[string]parser.Field{
					"id":   {Type: "id"},
					"name": {Type: "string"},
					"age":  {Type: "integer"},
				}),
			},
		}),
		Collections: makeCollections(map[string]parser.Collection{
			"users": {Model: "User"},
		}),
	}

	gen, tmpDir := newSwiftGen(t, schema)
	if err := gen.Generate(); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	code := readSwiftFile(t, tmpDir, "User.swift")

	if !strings.Contains(code, "public struct User: Codable, Identifiable, Sendable") {
		t.Error("expected User struct with Identifiable")
	}
	if !strings.Contains(code, "@DocumentID public var id: String?") {
		t.Error("expected DocumentID field")
	}
	if !strings.Contains(code, "public var name: String") {
		t.Error("expected name: String field")
	}
	if !strings.Contains(code, "public var age: Int") {
		t.Error("expected age: Int field")
	}
}

func TestSwiftGenerate_WithEnum(t *testing.T) {
	schema := &parser.Schema{
		Models: makeModels(map[string]parser.Model{
			"User": {
				Fields: makeFields(map[string]parser.Field{
					"status": {Type: "string", Enum: []string{"active", "inactive"}},
				}),
			},
		}),
		Collections: makeCollections(map[string]parser.Collection{
			"users": {Model: "User"},
		}),
	}

	gen, tmpDir := newSwiftGen(t, schema)
	if err := gen.Generate(); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	code := readSwiftFile(t, tmpDir, "User.swift")

	if !strings.Contains(code, "public enum UserStatus: String, Codable, Sendable") {
		t.Error("expected UserStatus enum")
	}
	if !strings.Contains(code, "case active") {
		t.Error("expected active case")
	}
	if !strings.Contains(code, "case inactive") {
		t.Error("expected inactive case")
	}
}

func TestSwiftGenerate_WithTimestamp(t *testing.T) {
	schema := &parser.Schema{
		Models: makeModels(map[string]parser.Model{
			"Post": {
				Fields: makeFields(map[string]parser.Field{
					"createdAt": {Type: "server_timestamp"},
				}),
			},
		}),
		Collections: makeCollections(map[string]parser.Collection{
			"posts": {Model: "Post"},
		}),
	}

	gen, tmpDir := newSwiftGen(t, schema)
	if err := gen.Generate(); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	code := readSwiftFile(t, tmpDir, "Post.swift")

	if !strings.Contains(code, "@ServerTimestamp public var createdAt: Date?") {
		t.Error("expected @ServerTimestamp field")
	}
}

func TestSwiftGenerate_WithSubcollection(t *testing.T) {
	schema := &parser.Schema{
		Models: makeModels(map[string]parser.Model{
			"Thread":  {Fields: makeFields(map[string]parser.Field{"title": {Type: "string"}})},
			"Message": {Fields: makeFields(map[string]parser.Field{"content": {Type: "string"}})},
		}),
		Collections: makeCollections(map[string]parser.Collection{
			"threads": {
				Model: "Thread",
				Path:  "threads/{threadID}",
				Subcollections: makeCollections(map[string]parser.Collection{
					"messages": {Model: "Message", Path: "threads/{threadID}/messages/{messageID}"},
				}),
			},
		}),
	}

	gen, tmpDir := newSwiftGen(t, schema)
	if err := gen.Generate(); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	code := readSwiftFile(t, tmpDir, "Thread.swift")

	if !strings.Contains(code, "public enum MessageCollection") {
		t.Error("expected MessageCollection enum for subcollection")
	}
	if !strings.Contains(code, "public static func collectionPath") {
		t.Error("expected collectionPath for subcollection")
	}
	if !strings.Contains(code, "public struct Message") {
		t.Error("expected Message struct in same file")
	}
}

func TestPackageSwiftTemplate(t *testing.T) {
	pkg := string(PackageSwiftTemplate)

	if !strings.Contains(pkg, "swift-tools-version") {
		t.Error("expected swift-tools-version in Package.swift template")
	}
	if !strings.Contains(pkg, "FirebaseFirestore") {
		t.Error("expected FirebaseFirestore dependency in Package.swift template")
	}
}
