#!/bin/bash
# scripts/generate_makefile_aggregate.sh

set -euo pipefail

cd "$(dirname "$0")/.."

SUBDIRS=()
for makefile in */Makefile; do
  SUBDIRS+=("$(dirname "$makefile")")
done

OUTPUT="Makefile.agg"

{
  echo "# This file is auto-generated by scripts/generate_makefile_aggregate.sh."
  echo "# Do not edit it by hand."
  echo "# When a target is added or removed in a subdirectory Makefile,"
  echo "# re-run \`make aggregate\` and commit the diff."

  for dir in "${SUBDIRS[@]}"; do
    targets=$(grep -oE '^[A-Za-z0-9][A-Za-z0-9_./-]*:' "$dir/Makefile" | sed 's/:$//' | sort -u)

    echo ""
    echo "# --- ${dir} ---"
    printf '.PHONY:'
    for target in $targets; do
      printf ' %s/%s' "$dir" "$target"
    done
    printf '\n'

    for target in $targets; do
      echo ""
      echo "${dir}/${target}:"
      printf '\tdirenv exec %s $(MAKE) -C %s %s\n' "$dir" "$dir" "$target"
    done
  done
} > "$OUTPUT"

echo "Generated $OUTPUT"
