name: CI Client
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      - name: Install swift-format
        run: brew install swift-format
      - name: Lint
        run: cd client && make ci-lint
