name: CI Functions
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths:
      - 'functions/**'
  pull_request:
    paths:
      - 'functions/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c #v6.4.0
        with:
          go-version-file: 'functions/go.mod'
      - uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee #v9.2.1
        with:
          working-directory: functions
          version: v2.12.2
          args: --enable=gosec
      - name: Setup
        run: cd functions && make setup SKIP_GOLANGCI_LINT=1
      - name: Vulncheck
        run: cd functions && make vulncheck

  # tag:
  #   needs: [lint]
  #   if: github.ref == 'refs/heads/main'
  #   permissions:
  #     contents: write
  #     pull-requests: read
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
  #     - uses: ./.github/actions/create-tag
  #       with:
  #         component: functions
