name: CI Functions
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths:
      - 'functions/**'
  pull_request:
    paths:
      - 'functions/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7.0.0
        with:
          go-version-file: 'functions/go.mod'
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a #v9.3.0
        with:
          working-directory: functions
          version: v2.12.2
          args: --enable=gosec
      - name: Setup
        run: cd functions && make setup SKIP_GOLANGCI_LINT=1
      - name: Vulncheck
        run: cd functions && make vulncheck

  # tag:
  #   needs: [lint]
  #   if: github.ref == 'refs/heads/main'
  #   permissions:
  #     contents: write
  #     pull-requests: read
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
  #     - uses: ./.github/actions/create-tag
  #       with:
  #         component: functions
